name: juso
description: Flutter package for address search in Korea
version: 1.0.0+1
repository: https://github.com/appano1/juso

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  flutter_lints: ^1.0.4
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/index.html